<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <!-- единственная платформа — Windows -->
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>

    <!-- выходной тип — GUI-приложение Windows -->
    <OutputType>WinExe</OutputType>

    <!-- MAUI -->
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- ВАЖНО: отключаем упаковку в MSIX -->
    <WindowsPackageType>MSIX</WindowsPackageType>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>74F4D1AEC1B946D8D08C934D60555DA42FEB3CDF</PackageCertificateThumbprint>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
    <PackageReference Include="FirebaseDatabase.net" Version="4.2.0" />
    <PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="Views\HomePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

  <ItemGroup>
    <None Update="Views\HomePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\LoginPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\RegistrationPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\WelcomePage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>